# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  cli:
    volumes:
        - ../../chaincode/demo:/opt/gopath/src/github.com/chaincode/demo
