extends:
  - eslint:recommended
  - airbnb-base
  - plugin:react/recommended
  - prettier
env:
  es6: true
  node: true
  browser: true
  jest: true
rules:
  no-console: 'off'
  no-plusplus: 'off'
  no-param-reassign: ['error', { props: false }]
  class-methods-use-this: 'off'
  curly: [error, all]
  comma-dangle: [error, never]
  prefer-destructuring: ['error', { VariableDeclarator: { object: false } }]
  no-underscore-dangle: ['error', { allow: ['_id'] }]
  camelcase:
    ['error', { allow: ['user_info', 'full_name', 'user_name', 'org_name'] }]
parserOptions:
  ecmaVersion: 9
  sourceType: module
settings:
  react:
    version: detect
plugins:
  - eslint-plugin-react
