version: '2'

services:

  app.org1.example.com:
    container_name: app.org1.example.com
    image: demo/app:latest
    restart: always
    ports:
      - 3001:3001
    volumes:
      - ./:/app/first-network
      - ../../wallets/org1:/app/wallet
      - ../../app/server:/app/server #only for quick debugging
    environment:
      ORG: org1
      DOMAIN: example.com
      LDAP_HOST: ldap.org1.example.com
      DEFAULT_HLF_CHANNEL: $CHANNEL_NAME
      DEFAULT_HLF_CHAINCODE: $CHAINCODE_NAME
      PORT: 3001
      JWT_SECRET: 5agw5lmRedJ2P01ryQDB
      ENCRYPTION_KEY: sgRYjFLaqB4o6i95L6khqIveRkpZPL37
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    networks:
      - byfn

  app.org2.example.com:
    container_name: app.org2.example.com
    image: demo/app:latest
    restart: always
    ports:
      - 3002:3002
    volumes:
      - ./:/app/first-network
      - ../../wallets/org2:/app/wallet
      - ../../app/server:/app/server #only for quick debugging
    environment:
      ORG: org2
      DOMAIN: example.com
      LDAP_HOST: ldap.org2.example.com
      DEFAULT_HLF_CHANNEL: $CHANNEL_NAME
      DEFAULT_HLF_CHAINCODE: $CHAINCODE_NAME
      PORT: 3002
      JWT_SECRET: 4HqMXDHyJeaoj0pnmkJ1
      ENCRYPTION_KEY: 42wp7IkGNY8mZBei741WXXRpzet9GaLi
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    networks:
      - byfn

